### ISSUE TITLE
Домашнее задание по промисам

### ISSUE THREAD

**Issue by tiny-kottan** [vrd/kottans-js-2016#6]
Написать `Promise.map`, `Promise.some` и `Promise.reduce`. Должно работать как в доках блуберда: http://bluebirdjs.com/docs/api-reference.html. Тесты: https://github.com/petkaantonov/bluebird/tree/master/test/mocha
Промис нужно сабклассить. `Promise.all` не юзать. Брать конструктор промиса из this

**Comment by vrd** [comment]
@shvaikalesh could you throw some tomatoes?
- MyPromise https://github.com/vrd/kottans-js-2016/blob/master/week04/lec1/mypromise.js
- tests (requires mocha and assert) https://github.com/vrd/kottans-js-2016/blob/master/week04/lec1/test.js

**Comment by shvaikalesh** [comment]
``` js
  constructor() {
    super(...arguments)
  }
```

is an extra, derived classes generate same code by themselves.

`static map(iterable, mapper) {`

``` js
      let started = 0
      let done = 0
```
1. Try accomplish the same with only 1 variable. Some examples were in the chat.
2. Promises do `typeof iter[Symbol.iterator] == 'function'` internally, but here you can just do `this.resolve(i)` and let js take care of thenables/non-thenables.
3. `},  reject)` .... in few lines `},  reject)` . Last is enough to reject returned promise.

Same ^^ goes for filter and reduce. Pretty minor stuff. Otherwise, very NICE job. Loved the comments.
